# Generated by Django 5.0.7 on 2025-11-21 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0003_mpesapayment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="currency",
            field=models.CharField(default="KES", max_length=3),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("mpesa", "M-Pesa"),
                    ("bank_transfer", "Bank Transfer"),
                    ("cash", "Cash"),
                ],
                default="mpesa",
                max_length=20,
            ),
        ),
    ]
