# Generated by Django 5.0.7 on 2026-01-12 11:16

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recipes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('category', models.CharField(choices=[('produce', 'Produce'), ('meat', 'Meat & Poultry'), ('seafood', 'Seafood'), ('dairy', 'Dairy & Eggs'), ('pantry', 'Pantry & Dry Goods'), ('frozen', 'Frozen'), ('beverages', 'Beverages'), ('bakery', 'Bakery'), ('other', 'Other')], default='other', max_length=50)),
                ('shelf_life_days', models.PositiveIntegerField(blank=True, help_text='Approximate shelf life in days', null=True)),
                ('calories_per_100g', models.PositiveIntegerField(blank=True, null=True)),
                ('is_common', models.BooleanField(default=False, help_text='Is this a common staple?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('substitutions', models.ManyToManyField(blank=True, to='kitchen.ingredient')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='KitchenInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=1.0, max_digits=10)),
                ('unit', models.CharField(default='pcs', max_length=20)),
                ('is_essential', models.BooleanField(default=False, help_text='Always restock this item')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_kitchens', to='kitchen.ingredient')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Kitchen Inventories',
            },
        ),
        migrations.CreateModel(
            name='MealSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('session_type', models.CharField(choices=[('cooked', 'Cooked at Home'), ('booked_chef', 'Booked a Chef'), ('ordered', 'Ordered Ingredients'), ('skipped', 'Skipped/Browsed')], default='cooked', max_length=20)),
                ('time_of_day', models.CharField(blank=True, max_length=20)),
                ('user_mood', models.CharField(blank=True, max_length=50)),
                ('weather_snapshot', models.CharField(blank=True, max_length=50)),
                ('was_completed', models.BooleanField(default=False)),
                ('rating', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('difficulty_score', models.PositiveIntegerField(blank=True, help_text="User's perceived effort (1-5)", null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('feedback_tags', models.JSONField(blank=True, default=list)),
                ('recipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipes.recipe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='ingredient',
            index=models.Index(fields=['name'], name='kitchen_ing_name_4412c5_idx'),
        ),
        migrations.AddIndex(
            model_name='ingredient',
            index=models.Index(fields=['category'], name='kitchen_ing_categor_9440d2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='kitcheninventory',
            unique_together={('user', 'ingredient')},
        ),
    ]
