# Generated by Django 5.0.7 on 2026-01-12 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0001_initial'),
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeingredient',
            name='ingredient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_in_recipes', to='kitchen.ingredient'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='name',
            field=models.CharField(help_text='Display name if different from standard', max_length=200),
        ),
    ]
