# Generated by Django 5.0.7 on 2025-11-21 21:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0003_chatsession_session_name_alter_chatsession_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="userpreferencelearning",
            name="preferred_price_range",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="userpreferencelearning",
            name="preferred_cuisines",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name="UserInteraction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        choices=[("chef", "Chef"), ("meal", "Meal")], max_length=10
                    ),
                ),
                ("content_id", models.PositiveIntegerField()),
                (
                    "interaction_type",
                    models.CharField(
                        choices=[
                            ("view", "View"),
                            ("like", "Like/Favorite"),
                            ("book", "Booking"),
                            ("share", "Share"),
                            ("skip", "Skip"),
                        ],
                        max_length=10,
                    ),
                ),
                ("weight", models.PositiveIntegerField(default=1)),
                ("session_id", models.CharField(blank=True, max_length=100)),
                ("device_type", models.CharField(blank=True, max_length=50)),
                ("duration_seconds", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "content_type", "-created_at"],
                        name="ai_userinte_user_id_95c427_idx",
                    ),
                    models.Index(
                        fields=["content_type", "content_id"],
                        name="ai_userinte_content_508189_idx",
                    ),
                ],
            },
        ),
    ]
