# Generated by Django 5.0.7 on 2025-11-27 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_menuitem_delivery_available_menuitem_ingredients_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='menu_items',
        ),
        migrations.AddField(
            model_name='booking',
            name='down_payment_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='is_priority',
            field=models.BooleanField(default=False, help_text='Client committed with a down payment'),
        ),
    ]
