# Generated by Django 5.2.8 on 2025-11-27 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0005_remove_booking_menu_items_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="menuitem",
            name="meal_prep_available",
            field=models.BooleanField(default=False),
        ),
    ]
